# Generated by Django 4.1.3 on 2022-11-16 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=4)),
                ('plays', models.IntegerField(default=0)),
                ('explicit', models.BooleanField(default=False)),
                ('album', models.ManyToManyField(to='myapp.album')),
                ('artist', models.ManyToManyField(to='myapp.artist')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.genre')),
                ('playlist', models.ManyToManyField(to='myapp.playlist')),
            ],
        ),
    ]
